fix(install): 🐛 wait up to 10 seconds for the root api key to be generated before trying to print it while tailing the final logs (avoid race condition)
Signed-off-by: badsectorlabs-erik <555113-badsectorlabs-erik@users.noreply.gitlab.com>

diff --git a/ludus-server/ansible/proxmox-install/templates/ludus-install-status.sh.j2 b/ludus-server/ansible/proxmox-install/templates/ludus-install-status.sh.j2
--- a/ludus-server/ansible/proxmox-install/templates/ludus-install-status.sh.j2
+++ b/ludus-server/ansible/proxmox-install/templates/ludus-install-status.sh.j2
@@ -20,6 +20,17 @@ else
         fi
     done
 
+    # Wait up to 10 seconds for root-api-key file to exist
+    count=0
+    while [ ! -f {{ ludus_install_path }}/install/root-api-key ] && [ $count -lt 10 ]; do
+        sleep 1
+        ((count++))
+    done
+    if [ ! -f {{ ludus_install_path }}/install/root-api-key ]; then
+        echo "Error: Root API key file ({{ ludus_install_path }}/install/root-api-key)not found"
+        exit 1
+    fi
+
     echo
     echo -n "Root API key: "
     cat {{ ludus_install_path }}/install/root-api-key
